scripts: resync all build scripts with master repo: https://github.com/RobertCNelson/linux-dev
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/patches/backports/bindeb-pkg/0001-backports-bindeb-pkg-from-linux.git.patch b/patches/backports/bindeb-pkg/0001-backports-bindeb-pkg-from-linux.git.patch
--- a/patches/backports/bindeb-pkg/0001-backports-bindeb-pkg-from-linux.git.patch
+++ b/patches/backports/bindeb-pkg/0001-backports-bindeb-pkg-from-linux.git.patch
@@ -1,15 +1,60 @@
-From 36ec086f59aba2659085bc3a0eabea87794d16eb Mon Sep 17 00:00:00 2001
+From bd8b65f74507059d7b3d0594d311ed5281b59d3e Mon Sep 17 00:00:00 2001
 From: Robert Nelson <robertcnelson@gmail.com>
-Date: Fri, 6 Mar 2020 19:39:52 -0600
+Date: Fri, 6 Mar 2020 21:59:17 -0600
 Subject: [PATCH] backports: bindeb-pkg: from: linux.git
 
 Reference: v5.1
 Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
 ---
+ scripts/package/Makefile |  9 ++---
  scripts/package/builddeb | 46 +++++++++++----------
  scripts/package/mkdebian | 86 ++++++++++++++++++++++++++++++----------
- 2 files changed, 90 insertions(+), 42 deletions(-)
+ 3 files changed, 94 insertions(+), 47 deletions(-)
 
+diff --git a/scripts/package/Makefile b/scripts/package/Makefile
+index 73503ebce632..2c6de21e5152 100644
+--- a/scripts/package/Makefile
++++ b/scripts/package/Makefile
+@@ -33,7 +33,6 @@ MKSPEC     := $(srctree)/scripts/package/mkspec
+ 
+ quiet_cmd_src_tar = TAR     $(2).tar.gz
+       cmd_src_tar = \
+-set -e; \
+ if test "$(objtree)" != "$(srctree)"; then \
+ 	echo >&2; \
+ 	echo >&2 "  ERROR:"; \
+@@ -60,7 +59,7 @@ rpm-pkg: FORCE
+ # binrpm-pkg
+ # ---------------------------------------------------------------------------
+ binrpm-pkg: FORCE
+-	$(MAKE) KBUILD_SRC=
++	$(MAKE) -f $(srctree)/Makefile
+ 	$(CONFIG_SHELL) $(MKSPEC) prebuilt > $(objtree)/binkernel.spec
+ 	+rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
+ 		$(UTS_MACHINE) -bb $(objtree)/binkernel.spec
+@@ -73,11 +72,11 @@ deb-pkg: FORCE
+ 	$(call cmd,src_tar,$(KDEB_SOURCENAME))
+ 	origversion=$$(dpkg-parsechangelog -SVersion |sed 's/-[^-]*$$//');\
+ 		mv $(KDEB_SOURCENAME).tar.gz ../$(KDEB_SOURCENAME)_$${origversion}.orig.tar.gz
+-	+dpkg-buildpackage -r$(KBUILD_PKG_ROOTCMD) -a$$(cat debian/arch) -i.git -us -uc
++	+dpkg-buildpackage -r$(KBUILD_PKG_ROOTCMD) -a$$(cat debian/arch) $(DPKG_FLAGS) -i.git -us -uc
+ 
+ bindeb-pkg: FORCE
+ 	$(CONFIG_SHELL) $(srctree)/scripts/package/mkdebian
+-	+dpkg-buildpackage -r$(KBUILD_PKG_ROOTCMD) -a$$(cat debian/arch) -b -nc -uc
++	+dpkg-buildpackage -r$(KBUILD_PKG_ROOTCMD) -a$$(cat debian/arch) $(DPKG_FLAGS) -b -nc -uc
+ 
+ intdeb-pkg: FORCE
+ 	+$(CONFIG_SHELL) $(srctree)/scripts/package/builddeb
+@@ -103,7 +102,7 @@ clean-dirs += $(objtree)/snap/
+ # tarball targets
+ # ---------------------------------------------------------------------------
+ tar%pkg: FORCE
+-	$(MAKE) KBUILD_SRC=
++	$(MAKE) -f $(srctree)/Makefile
+ 	$(CONFIG_SHELL) $(srctree)/scripts/package/buildtar $@
+ 
+ clean-dirs += $(objtree)/tar-install/
 diff --git a/scripts/package/builddeb b/scripts/package/builddeb
 index 90c9a8ac7adb..b03dd56a4782 100755
 --- a/scripts/package/builddeb
